server:
    port: 8230

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    
metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: highestbid

http:
    cache:
        timeToLiveInDays: 31
